### ISSUE TITLE
Use my own data while developing a fork of the project.

### ISSUE THREAD

**Issue by g0d13** [mrLuisFer/linktry#9]
I really love your project and looks pretty nice. 
I want to add some features to the code, but how do I develop and maintain my own data?

**Comment by mrLuisFer** [comment]
Inside the project there is a folder called Api, it is not an api as such it is a simulation in which you can add your data, use it within the application and even add new

[github/mrLuisFer/linktry/main/src/api](https://github.com/mrLuisFer/linktry/tree/main/src/api)

**Comment by mrLuisFer** [comment]
I am going to close the issue, if you still have doubts you can open it again or create a new issue with your question
